### PR TITLE
Nilupmf

### PR DESCRIPTION
**Pull request by dulte**
Reader for the well structured part of the NILU PMF data. Might be redundant if a new EBAS reader is implemented

### CODE REVIEW

**Comment by dulte** [comment]
Needs tests

**Comment by dulte** [comment]
Won't work on this until #35 is done, to see if that reader is able to read the same data

**Comment by jgriesfeller** [comment]
Trying to finish this for the AeroTools release since only linting was going wrong

**Comment by jgriesfeller** [comment]
@thorbjoernl I just realised test are missing. No need to note that in the review.

**Comment by jgriesfeller** [comment]
This needs a bit more work than I thought (I thought only linting was missing). But there's no tests and if one supllies a directory the data has to be in certain directory below that. This is not how is should be.
Leaving the work to @dulte therefore.

**Comment by jgriesfeller** [comment]
small comment on the Absorption files: 
They are not EBAS NASA-AMES compliant (are missing vital metadata like `matrix` and `component`) and can therefore **not** be read with the `nilupmfebas` reader.
The current implementation depends a bit too much on the files to have a certain format in the header, but since it works for this particular set of files, I kept @dulte 's implementation

**Review by thorbjoernl — APPROVED** [review]
LGTM

**Pull request merged**
